version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y jq
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade --force-reinstall "botocore>1.21.30" "boto3>1.18.30" "awscli>1.20.30"

  build:
    commands:
      # Export the staging and production configuration files
      - python build.py --model-execution-role "$MODEL_EXECUTION_ROLE_ARN" --model-package-group-name "$SOURCE_MODEL_PACKAGE_GROUP_NAME" --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --s3-bucket "$ARTIFACT_BUCKET" --export-staging-config $EXPORT_TEMPLATE_STAGING_CONFIG --export-prod-config $EXPORT_TEMPLATE_PROD_CONFIG

      # Package the infrastucture as code defined in endpoint-config-template.yml by using AWS CloudFormation.
      # Note that the Environment Variables like ARTIFACT_BUCKET, SAGEMAKER_PROJECT_NAME etc,. used below are expected to be setup by the
      # CodeBuild resrouce in the infra pipeline (in the ServiceCatalog product)
      - aws cloudformation package --template endpoint-config-template.yml --s3-bucket $ARTIFACT_BUCKET --output-template $EXPORT_TEMPLATE_NAME

      # Print the files to verify contents
      - cat $EXPORT_TEMPLATE_NAME
      - cat $EXPORT_TEMPLATE_STAGING_CONFIG
      - cat $EXPORT_TEMPLATE_PROD_CONFIG
      - MODEL_PACKAGE_NAME=$(cat $EXPORT_TEMPLATE_PROD_CONFIG | jq -r '.Parameters.ModelPackageName')
      - echo $MODEL_PACKAGE_NAME
      - echo "{\"ModelPackageName\":\"$MODEL_PACKAGE_NAME\",\"ModelExecutionRoleArn\":\"$MODEL_EXECUTION_ROLE_ARN\"}" > model_info.json

artifacts:
  files:
    - $EXPORT_TEMPLATE_NAME
    - $EXPORT_TEMPLATE_STAGING_CONFIG
    - $EXPORT_TEMPLATE_PROD_CONFIG
    - model_info.json
#    - model_package_info.txt
#    - model_execution_info.txt
#  secondary-artifacts:
#    ModelPackageInfoOutput:
#      files:
#        - model_info.txt
